// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PetProductivity.Server.Data;

#nullable disable

namespace PetProductivity.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260703225033_AddRevivalProgress")]
    partial class AddRevivalProgress
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PetProductivity.Shared.Models.FocusProof", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<byte[]>("Image")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Plausible")
                        .HasColumnType("boolean");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SessionId", "UserId");

                    b.ToTable("FocusProofs");
                });

            modelBuilder.Entity("PetProductivity.Shared.Models.FocusSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("PetId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("TargetMinutes")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "PetId");

                    b.ToTable("FocusSessions");
                });

            modelBuilder.Entity("PetProductivity.Shared.Models.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ComboExpiry")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<double>("CurrentMultiplier")
                        .HasColumnType("double precision");

                    b.Property<int>("GroupArchetype")
                        .HasColumnType("integer");

                    b.Property<string>("InviteCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MaxMembers")
                        .HasColumnType("integer");

                    b.Property<string>("MemberIds")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SharedPetId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("InviteCode")
                        .IsUnique();

                    b.HasIndex("SharedPetId")
                        .IsUnique();

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("PetProductivity.Shared.Models.GroupFocusSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<string>("Participants")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PetId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("TargetMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("GroupFocusSessions");
                });

            modelBuilder.Entity("PetProductivity.Shared.Models.GroupMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GroupId", "UserId")
                        .IsUnique();

                    b.ToTable("GroupMemberships");
                });

            modelBuilder.Entity("PetProductivity.Shared.Models.JoinRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Approvals")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("RequesterUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GroupId", "RequesterUserId")
                        .IsUnique();

                    b.ToTable("JoinRequests");
                });

            modelBuilder.Entity("PetProductivity.Shared.Models.Pet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CurrentArchetype")
                        .HasColumnType("integer");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<int>("GoldCoins")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("GracePeriodExpiry")
                        .HasColumnType("timestamp without time zone");

                    b.Property<double>("Happiness")
                        .HasColumnType("double precision");

                    b.Property<double>("Health")
                        .HasColumnType("double precision");

                    b.Property<double>("Hunger")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("LastDecayAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("LastRevivalCreditDay")
                        .HasColumnType("timestamp without time zone");

                    b.Property<double>("MaxHealth")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RevivalProgress")
                        .HasColumnType("integer");

                    b.Property<int>("Species")
                        .HasColumnType("integer");

                    b.Property<string>("Stats")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<double>("TotalXp")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Pets");

                    b.HasDiscriminator().HasValue("Pet");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("PetProductivity.Shared.Models.TaskApproval", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Approvals")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Difficulty")
                        .HasColumnType("integer");

                    b.Property<int>("GoldEarned")
                        .HasColumnType("integer");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PetId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RequesterUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("XpEarned")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("TaskApprovals");
                });

            modelBuilder.Entity("PetProductivity.Shared.Models.TaskItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AiDifficultyScore")
                        .HasColumnType("integer");

                    b.Property<string>("AiStatCategory")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("GoldEarned")
                        .HasColumnType("integer");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PetId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ProofId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProofVerdict")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("XpEarned")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProofId");

                    b.HasIndex("PetId", "CreatedAt");

                    b.HasIndex("UserId", "CreatedAt");

                    b.ToTable("TaskItems");
                });

            modelBuilder.Entity("PetProductivity.Shared.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActiveRoomStyle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("ActiveXpMultiplier")
                        .HasColumnType("double precision");

                    b.Property<int>("CurrentStatus")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentStreak")
                        .HasColumnType("integer");

                    b.Property<string>("DeviceToken")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FocusStreak")
                        .HasColumnType("integer");

                    b.Property<string>("Inventory")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastActivityDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("LastFocusDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("LastNotifications")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LastRitualReset")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("LastSync")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("MaxFocusStreak")
                        .HasColumnType("integer");

                    b.Property<int>("MaxStreak")
                        .HasColumnType("integer");

                    b.Property<bool>("NotificationsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PlacedFurniture")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RitualGridState")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RitualLabels")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ThemePreference")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TotalFocusMinutes")
                        .HasColumnType("integer");

                    b.Property<int>("TotalTasksCompleted")
                        .HasColumnType("integer");

                    b.Property<Guid?>("UserPetId")
                        .HasColumnType("uuid");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("UserPetId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PetProductivity.Shared.Models.SharedPet", b =>
                {
                    b.HasBaseType("PetProductivity.Shared.Models.Pet");

                    b.Property<string>("HatchVotes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsHatched")
                        .HasColumnType("boolean");

                    b.Property<string>("UserAffection")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("SharedPet");
                });

            modelBuilder.Entity("PetProductivity.Shared.Models.Group", b =>
                {
                    b.HasOne("PetProductivity.Shared.Models.SharedPet", "SharedPet")
                        .WithOne()
                        .HasForeignKey("PetProductivity.Shared.Models.Group", "SharedPetId");

                    b.Navigation("SharedPet");
                });

            modelBuilder.Entity("PetProductivity.Shared.Models.User", b =>
                {
                    b.HasOne("PetProductivity.Shared.Models.Pet", "UserPet")
                        .WithMany()
                        .HasForeignKey("UserPetId");

                    b.Navigation("UserPet");
                });
#pragma warning restore 612, 618
        }
    }
}
